In [1]:
from linear_dag.core.brick_graph import BrickGraph
import scipy.sparse as sp
import h5py
import numpy as np

In [2]:
genotypes = sp.load_npz('/Users/ambershen/Desktop/linARG/brick_graph_vis/linear_args/HLA_chr6-32578775-32579775_whitelist_test/genotype_matrices/0_chr6-32578775-32588775.npz')
forward_graph, backward_graph, sample_indices = BrickGraph.forward_backward(genotypes)

In [ ]:
BrickGraph.forward_backward(genotypes, save_to_disk=True, out='test')

In [3]:
with h5py.File('/Users/ambershen/Desktop/linARG/dx_analysis/test_pipeline/linear_args/forward_backward_graphs/0_chr6-32578775-32588775_forward_graph.h5', 'r') as f:
    forward_graph_from_h5 = sp.csr_matrix((f['data'][:], f['indices'][:], f['indptr'][:]), shape=(f.attrs['n'], f.attrs['n']))
    
with h5py.File('/Users/ambershen/Desktop/linARG/dx_analysis/test_pipeline/linear_args/forward_backward_graphs/0_chr6-32578775-32588775_backward_graph.h5', 'r') as f:
    backward_graph_from_h5 = sp.csr_matrix((f['data'][:], f['indices'][:], f['indptr'][:]), shape=(f.attrs['n'], f.attrs['n']))

In [33]:
with h5py.File('/Users/ambershen/Desktop/linARG/dx_analysis/test_pipeline/linear_args/forward_backward_graphs/0_chr6-32578775-32588775_forward_graph.h5', 'r') as f:
    forward_graph_from_h5 = sp.csr_matrix((f['data'][:], f['indices'][:], f['indptr'][:]), shape=(f.attrs['n'], f.attrs['n']))
    
with h5py.File('/Users/ambershen/Desktop/linARG/dx_analysis/test_pipeline/linear_args/forward_backward_graphs/0_chr6-32578775-32588775_backward_graph.h5', 'r') as f:
    backward_graph_from_h5 = sp.csr_matrix((f['data'][:], f['indices'][:], f['indptr'][:]), shape=(f.attrs['n'], f.attrs['n']))

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 121357 stored elements and shape (2774, 2774)>

In [34]:
forward_graph_from_h5

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 21357 stored elements and shape (2774, 2774)>

In [37]:
backward_graph.to_csr() - backward_graph_from_h5

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 1184 stored elements and shape (2774, 2774)>

In [36]:
backward_graph_from_h5

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 1010 stored elements and shape (2774, 2774)>

In [11]:
matrix

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 21357 stored elements and shape (2774, 2774)>

In [13]:
forward_graph.to_csr()

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 121357 stored elements and shape (2774, 2774)>

In [8]:
linarg_dir = '/Users/ambershen/Desktop/linARG/test_pipeline/linear_args/'
partition_identifier = '0_chr6-32578775-32588775'

with h5py.File(f'{linarg_dir}/forward_backward_graphs/{partition_identifier}_forward_graph.h5', 'r') as f:
    forward_graph = sp.csr_matrix((f['data'][:], f['indices'][:], f['indptr'][:]), shape=(f.attrs['n'], f.attrs['n']))

with h5py.File(f'{linarg_dir}/forward_backward_graphs/{partition_identifier}_backward_graph.h5', 'r') as f:
    backward_graph = sp.csr_matrix((f['data'][:], f['indices'][:], f['indptr'][:]), shape=(f.attrs['n'], f.attrs['n']))

In [9]:
forward_graph.diagonal()

array([0., 0., 0., ..., 0., 0., 0.])

In [14]:
backward_graph.diagonal()

array([11.,  0.,  0., ...,  0.,  0.,  0.])

In [18]:
forward_graph.nonzero()

(array([0, 0, 0, ..., 0, 0, 0], dtype=int32),
 array([1932, 1935,  593, ..., 1389, 1394, 1411], dtype=int32))

In [21]:
set(forward_graph.data)

{1.0}

In [22]:
set(backward_graph.data)

{1.0}

In [23]:
# Get the actual data at position (0,0)
print("Value at (0,0):", backward_graph[0,0])

# Get all diagonal elements with their positions
rows, cols = backward_graph.nonzero()
diag_mask = rows == cols
print("\nAll diagonal elements:")
for r, c in zip(rows[diag_mask], cols[diag_mask]):
    print(f"({r}, {c}): {backward_graph[r,c]}")

Value at (0,0): 11.0

All diagonal elements:
(0, 0): 11.0
(0, 0): 11.0
(0, 0): 11.0
(0, 0): 11.0
(0, 0): 11.0
(0, 0): 11.0
(0, 0): 11.0
(0, 0): 11.0
(0, 0): 11.0
(0, 0): 11.0
(0, 0): 11.0
